services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_WS_URL=ws://localhost:8080

  server:
    build: ./server
    ports:
      - "8080:8080"
