name: CI Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  build-client:
    name: Build Client Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Client Image
        run: |
          docker build -t log-viewer-client ./client

  build-server:
    name: Build Server Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Server Image
        run: |
          docker build -t log-viewer-server ./server
